### ISSUE TITLE
The long-awaited mod is finally developed, thanks to the developers

### ISSUE THREAD

**Issue by aopkcn** [Tristan-dvr/ServerLocalization#1]
The long-awaited mod is finally developed, thanks to the developers
At present, I found in the test that only the localized content in the ontology can be localized,
Normally: "item_stone": "Stone"
Is it possible to localize content without $?
For example: "Stone":"Stone11"
If it can be achieved, then all text or other mods in the game can be localized,
Thanks to the developers.

**Comment by Tristan-dvr** [comment]
> localized content in the ontology can be localized

Yes, mod just update localized texts, but doesnt add localization to assets if they not localized. For example, if some mod has no localization my mod cannot  localize his assets.


> Is it possible to localize content without $?

It may be tricky. Normally mod devs adds localization to their mods and you can replace it. If mod asset names and descriptions are hardcoded so the mod need to modify the assets, but not just localization. And it is not the thing my mod created for) In this case you can use WackyDatabase to modify these assets, add them localizaton tags instead of hardcoded texts and localize them with ServerLocalization. But better ask mod developer to add localization to his mod)
